Updated EL DCA configuration
Sage-Bionetworks/data_curator_config pull request #84
Opened 2023-08-03 21:44 UTC by nlee-sage

Removed the study template as it is not functional currently.

2023-08-03 21:48 UTC, afwillia requested changes

2023-08-03 21:48 UTC, afwillia commented on EL/dca-template-config.json
> +      "type": "records"
`records` needs to be `record`

2023-09-14 00:23 UTC, nlee-sage commented
Updated EL DCA configuration and data model .jsonld URL

2023-09-14 00:25 UTC, nlee-sage commented on EL/dca-template-config.json
> +      "type": "records"
Updated configuration based on comment

2023-09-14 16:01 UTC, merged